export { Board } from './Board'
export { SquareContainer } from './Square'
export { GameContainer } from "./Game";
export { TotalScore } from "./TotalScore";
export { GameInfo } from "./GameInfo";
export { Timer } from  './Timer'
export { GamesContainer } from "./Games";
export { GamesMenu } from './GamesMenu';
export { OnLinePageContainer } from "./OnLinePage";
export { OffLinePageContainer } from './OffLinePage';
export { HomePageContainer } from './HomePage';