const ADD_SQUARE = 'ADD_SQUARE';
const CUT = 'CUT';
const CHANGE_STEP = 'CHANGE_STEP';
const CHANGE_XISNEXT = 'CHANGE_XISNEXT';
const ADD_NEW_GAME = 'ADD_NEW_GAME';
const LOSE_POINTS = "LOSE_POINTS";

export {
  ADD_SQUARE,
  CUT,
  CHANGE_STEP,
  CHANGE_XISNEXT,
  ADD_NEW_GAME,
  LOSE_POINTS
};