const SET_LOGGED_STATUS = "SET_LOGGED_STATUS";
const SET_PLAYER_STATUS = "SET_PLAYER_STATUS";
const SET_PLAYERS = "SET_PLAYERS";
const SET_SERVER_NOTIFICATION = "SET_SERVER_NOTIFICATION";

export {
  SET_LOGGED_STATUS,
  SET_PLAYER_STATUS,
  SET_PLAYERS,
  SET_SERVER_NOTIFICATION,
};