const SET_LOGGED_STATUS = "SET_LOGGED_STATUS";
const SET_PLAYER_STATUS = "SET_PLAYER_STATUS";
const SET_PLAYERS = "SET_PLAYERS";
const SET_SERVER_NOTIFICATION = "SET_SERVER_NOTIFICATION";
const GET_PLAYER_REQUESTED = "GET_PLAYER_REQUESTED";
const POST_PLAYER_REQUESTED = "POST_PLAYER_REQUESTED";
const SET_SOCKET_DATA = "SET_SOCKET_DATA";
const LOGOUT = "LOGOUT";
const UPDATE_PLAYERS_ONLINE = "UPDATE_PLAYERS_ONLINE";
const CREATE_GAME = "CREATE_GAME";


export {
  SET_LOGGED_STATUS,
  SET_PLAYER_STATUS,
  SET_PLAYERS,
  SET_SERVER_NOTIFICATION,
  GET_PLAYER_REQUESTED,
  POST_PLAYER_REQUESTED,
  SET_SOCKET_DATA,
  LOGOUT,
  UPDATE_PLAYERS_ONLINE,
  CREATE_GAME
};