const SET_LOGGED_STATUS = "SET_LOGGED_STATUS";
const SET_PLAYER_STATUS = "SET_PLAYER_STATUS";
const SET_PLAYERS = "SET_PLAYERS";
const SET_SERVER_NOTIFICATION = "SET_SERVER_NOTIFICATION";
const GET_PLAYER_REQUESTED = "GET_PLAYER_REQUESTED";


export {
  SET_LOGGED_STATUS,
  SET_PLAYER_STATUS,
  SET_PLAYERS,
  SET_SERVER_NOTIFICATION,
  GET_PLAYER_REQUESTED,
};